
import React, { useState, useEffect, useRef } from 'react';
import { 
  BarChart, 
  Briefcase, 
  Lightbulb, 
  AlertTriangle, 
  TrendingUp, 
  History,
  PieChart as PieChartIcon,
  MessageSquarePlus,
  Activity,
  Layout,
  Grid,
  Maximize2,
  Minimize2,
  X,
  Clock,
  ChevronDown,
  ChevronUp,
  FileText,
  Users,
  ChevronLeft,
  Radar as RadarIcon,
  CheckCircle,
  Search,
  Save,
  Globe,
  Target,
  DollarSign
} from 'lucide-react';
import { 
  ComposedChart, 
  Line, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  Legend, 
  ResponsiveContainer,
  Area, 
  Radar,
  RadarChart, 
  PolarGrid, 
  PolarAngleAxis, 
  PolarRadiusAxis,
  BarChart as RechartsBarChart,
  LineChart as RechartsLineChart,
  AreaChart as RechartsAreaChart
} from 'recharts';
import { ReportData, Metric, ReportTemplate, SectionId, Annotation, ReportViewMode, ReportSection, Risk, User } from '../types';
import MarkdownText from './MarkdownText';
import PredictiveAnalytics from './PredictiveAnalytics';

interface ReportViewProps {
  /** The full report data object generated by the AI or loaded from history */
  data: ReportData | null;
  /** Boolean indicating if the report is currently being generated/loading */
  isGenerating: boolean;
  /** The current visual template applied to the report */
  template: ReportTemplate;
  /** Callback when the template structure (sections, order) is modified by the user */
  onUpdateTemplate: (template: ReportTemplate) => void;
  /** NEW: Callback to update the master report data object in parent state */
  onReportUpdate?: (updatedData: ReportData) => void;
  /** Visual mode: 'document' (vertical scroll) or 'dashboard' (grid) */
  viewMode: ReportViewMode;
  /** Enterprise branding configuration */
  branding?: { logoUrl?: string; primaryColor?: string; companyName?: string; };
  /** The currently logged in user (used for permissions/RBAC) */
  user: User | null;
  /** NEW: Whether this component is currently visible (active tab) */
  isVisible?: boolean;
  /** Add toast notification */
  addToast?: (type: 'success' | 'error' | 'info', message: string) => void;
  /** Theme state for charts */
  isDarkMode?: boolean;
}

const MetricCard: React.FC<{ metric: Metric, themeColor: string }> = ({ metric, themeColor }) => (
  <div className="bg-white dark:bg-gray-800 p-6 rounded-2xl border border-gray-100 dark:border-gray-700 shadow-sm hover:shadow-lg hover:-translate-y-1 transition-all group page-break-inside-avoid relative overflow-hidden focus-within:ring-2 focus-within:ring-brand-accent" tabIndex={0} aria-label={`${metric.label}: ${metric.value}, trend ${metric.trend}%`}>
    {/* Background Pattern */}
    <div className="absolute top-0 right-0 w-24 h-24 bg-gradient-to-br from-transparent to-gray-50 dark:to-white/5 rounded-bl-full -mr-8 -mt-8 pointer-events-none"></div>
    
    <div className="flex justify-between items-start mb-4 relative z-10">
      <div className={`p-3 rounded-xl bg-gray-50 dark:bg-gray-700/50 text-gray-500 dark:text-gray-400 group-hover:bg-brand-accent/10 group-hover:text-brand-accent transition-colors`}>
         {metric.iconType === 'volume' && <BarChart size={20} />}
         {metric.iconType === 'trend' && <TrendingUp size={20} />}
         {metric.iconType === 'growth' && <Activity size={20} />}
         {metric.iconType === 'chart' && <PieChartIcon size={20} />}
      </div>
      {metric.trend !== 0 && (
          <div className={`text-xs font-bold px-2 py-1 rounded-full flex items-center gap-1 ${
              metric.trend > 0 ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' : 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400'
          }`}>
              {metric.trend > 0 ? '↑' : '↓'} {Math.abs(metric.trend)}%
          </div>
      )}
    </div>
    <div className="text-3xl font-black text-gray-900 dark:text-white mb-1 tracking-tight truncate relative z-10">{metric.value}</div>
    <span className="text-xs font-medium text-gray-400 uppercase tracking-wider truncate max-w-full block relative z-10">{metric.label}</span>
  </div>
);

const RiskMatrix: React.FC<{ risks: Risk[], themeColor: string }> = ({ risks, themeColor }) => {
    const [selectedRisk, setSelectedRisk] = useState<Risk | null>(null);

    const getCoordinates = (risk: Risk) => {
        let x = 0, y = 0;
        switch(risk.impact) {
            case 'Low': x = 1; break;
            case 'Medium': x = 2; break;
            case 'High': x = 3; break;
        }
        switch(risk.priority) {
            case 'Low': y = 1; break;
            case 'Monitor': y = 2; break;
            case 'Critical': y = 3; break;
        }
        // Use deterministic randomness based on char code to keep dots stable across renders
        const seed = risk.id.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
        const randomOffset = (seed % 40 - 20) / 100; // -0.2 to 0.2
        
        return { x: x + randomOffset, y: y + randomOffset, risk };
    };

    const plottedRisks = React.useMemo(() => risks.map(getCoordinates), [risks]);

    return (
        <div className="flex flex-col gap-4">
            <div className="h-[300px] w-full relative bg-gray-50 dark:bg-gray-900/50 rounded-xl border border-gray-200 dark:border-gray-700 p-4 print:border-black">
                <div className="absolute inset-0 grid grid-cols-3 grid-rows-3 p-8 pb-12 pl-12 gap-1 pointer-events-none">
                    {/* Grid Backgrounds */}
                    {[...Array(9)].map((_, i) => (
                         <div key={i} className={`border border-dashed border-gray-300 dark:border-gray-600 ${
                             [0,3,6,7].includes(i) ? 'bg-green-100/30 dark:bg-green-900/10' :
                             [1,4,8].includes(i) ? 'bg-yellow-100/30 dark:bg-yellow-900/10' :
                             'bg-red-100/30 dark:bg-red-900/10'
                         }`}></div>
                    ))}
                </div>

                <div className="absolute bottom-2 left-12 right-8 flex justify-between text-xs font-bold text-gray-400 uppercase">
                    <span>Low Impact</span>
                    <span>High Impact</span>
                </div>
                <div className="absolute top-8 bottom-12 left-2 flex flex-col justify-between text-xs font-bold text-gray-400 uppercase h-full py-4" style={{writingMode: 'vertical-lr', transform: 'rotate(180deg)'}}>
                    <span>Critical Priority</span>
                    <span>Low Priority</span>
                </div>

                <div className="absolute inset-0 p-8 pb-12 pl-12 z-10">
                    {plottedRisks.map((item, idx) => (
                        <button 
                            key={idx}
                            onClick={() => setSelectedRisk(selectedRisk?.id === item.risk.id ? null : item.risk)}
                            className="absolute w-5 h-5 rounded-full shadow-lg border-2 border-white dark:border-gray-800 transform -translate-x-1/2 -translate-y-1/2 hover:scale-125 transition-all cursor-pointer group flex items-center justify-center print:border-black hover:z-[100] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand-accent"
                            style={{
                                left: `${((item.x - 0.5) / 3) * 100}%`,
                                bottom: `${((item.y - 0.5) / 3) * 100}%`,
                                backgroundColor: item.risk.priority === 'Critical' ? '#EF4444' : item.risk.priority === 'Monitor' ? '#F59E0B' : '#10B981',
                                zIndex: selectedRisk?.id === item.risk.id ? 100 : 20,
                                transform: selectedRisk?.id === item.risk.id ? 'translate(-50%, -50%) scale(1.5)' : 'translate(-50%, -50%)'
                            }}
                        >
                            <div className={`absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-64 bg-gray-900 text-white text-xs p-3 rounded-lg shadow-xl transition-all duration-200 z-50 flex flex-col gap-1 no-print ${
                                selectedRisk?.id === item.risk.id ? 'opacity-100 visible' : 'opacity-0 invisible group-hover:opacity-100 group-hover:visible'
                            }`}>
                                <div className="flex justify-between items-center border-b border-gray-700 pb-1 mb-1">
                                    <span className="font-bold uppercase tracking-wider text-[10px] text-gray-400">Risk Details</span>
                                    <span className={`px-1.5 py-0.5 rounded text-[10px] font-bold ${
                                        item.risk.priority === 'Critical' ? 'bg-red-500/20 text-red-400' :
                                        item.risk.priority === 'Monitor' ? 'bg-orange-500/20 text-orange-400' :
                                        'bg-green-500/20 text-green-400'
                                    }`}>
                                        {item.risk.priority}
                                    </span>
                                </div>
                                <p className="font-medium leading-snug">{item.risk.description}</p>
                                <div className="absolute top-full left-1/2 -translate-x-1/2 -mt-[1px] border-4 border-transparent border-t-gray-900"></div>
                            </div>
                        </button>
                    ))}
                </div>
            </div>
            
            <div className="flex flex-wrap justify-center gap-6 text-xs text-gray-500 dark:text-gray-400">
                <div className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full bg-red-500 border border-white dark:border-gray-800 shadow-sm"></div>
                    <span>Critical Priority</span>
                </div>
                <div className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full bg-orange-400 border border-white dark:border-gray-800 shadow-sm"></div>
                    <span>Monitor Priority</span>
                </div>
                <div className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full bg-green-400 border border-white dark:border-gray-800 shadow-sm"></div>
                    <span>Low Priority</span>
                </div>
            </div>
        </div>
    );
};

const CustomTooltip = ({ active, payload, label }: any) => {
    if (active && payload && payload.length) {
        return (
            <div className="bg-white dark:bg-gray-800 p-3 border border-gray-200 dark:border-gray-700 shadow-lg rounded-lg">
                <p className="font-bold text-gray-900 dark:text-white mb-2 text-sm">{label}</p>
                {payload.map((entry: any, index: number) => (
                    <div key={index} className="flex items-center gap-2 text-xs mb-1">
                        <div className="w-2 h-2 rounded-full" style={{ backgroundColor: entry.color || entry.fill }} />
                        <span className="text-gray-500 dark:text-gray-400">{entry.name}:</span>
                        <span className="font-mono font-bold text-gray-700 dark:text-gray-200">
                            {entry.value.toLocaleString()}
                        </span>
                    </div>
                ))}
            </div>
        );
    }
    return null;
};

const ReportView: React.FC<ReportViewProps> = ({ data, isGenerating, template, onUpdateTemplate, onReportUpdate, viewMode, branding, user, isVisible = true, addToast, isDarkMode = false }) => {
  const [localReportData, setLocalReportData] = useState<ReportData | null>(null);
  const [visibleSeries, setVisibleSeries] = useState<string[]>(['primary', 'secondary']);
  const [showHistory, setShowHistory] = useState(false);
  const [activePersona, setActivePersona] = useState<'cfo'|'cro'|'coo'>('cro');
  
  // Annotation Modal State
  const [showNoteModal, setShowNoteModal] = useState(false);
  const [activeSectionForNote, setActiveSectionForNote] = useState<SectionId | null>(null);
  const [noteText, setNoteText] = useState('');

  const [isEditingTitle, setIsEditingTitle] = useState(false);
  const [viewTypeRisk, setViewTypeRisk] = useState<'list' | 'matrix'>('matrix');
  const [searchTerm, setSearchTerm] = useState('');
  const [showSearch, setShowSearch] = useState(false);

  // Table Sorting & Filtering State
  const [tableSort, setTableSort] = useState<{key: string, dir: 'asc' | 'desc'}>({key: 'contribution', dir: 'desc'});
  const [tableFilter, setTableFilter] = useState('');
  
  // Drill Down State
  const [drillDownLabel, setDrillDownLabel] = useState<string | null>(null);

  const chartContainerRef = useRef<HTMLDivElement>(null);
  const canEdit = true;

  useEffect(() => {
      if (data) setLocalReportData(data);
  }, [data]);

  const { theme } = template;

  const chartDataToRender = React.useMemo(() => {
    if (!localReportData) return [];
    if (drillDownLabel) {
        const parent = localReportData.chartData.find(d => d.name === drillDownLabel);
        if (!parent) return [];
        
        // Simulate weekly breakdown for drill-down with clear labels
        return [
            { name: `${drillDownLabel} W1`, primary: Math.round(parent.primary * 0.22), secondary: Math.round(parent.secondary * 0.20), amt: parent.amt * 0.2 },
            { name: `${drillDownLabel} W2`, primary: Math.round(parent.primary * 0.28), secondary: Math.round(parent.secondary * 0.25), amt: parent.amt * 0.25 },
            { name: `${drillDownLabel} W3`, primary: Math.round(parent.primary * 0.24), secondary: Math.round(parent.secondary * 0.28), amt: parent.amt * 0.25 },
            { name: `${drillDownLabel} W4`, primary: Math.round(parent.primary * 0.26), secondary: Math.round(parent.secondary * 0.27), amt: parent.amt * 0.3 }
        ];
    }
    return localReportData.chartData;
  }, [localReportData, drillDownLabel]);

  const openNoteModal = (sectionId: string) => {
      if (!canEdit) {
          addToast?.('error', 'You do not have permission to add notes.');
          return;
      }
      setActiveSectionForNote(sectionId as SectionId);
      setNoteText('');
      setShowNoteModal(true);
  };

  const handleSaveNote = () => {
      if (noteText.trim() && localReportData && activeSectionForNote) {
          const newNote: Annotation = {
              id: Date.now().toString(),
              sectionId: activeSectionForNote,
              text: noteText.trim(),
              author: user?.name || 'User',
              date: new Date()
          };
          
          const updatedReport = {
              ...localReportData,
              annotations: [...(localReportData.annotations || []), newNote]
          };

          setLocalReportData(updatedReport);
          if (onReportUpdate) onReportUpdate(updatedReport);

          addToast?.('success', 'Annotation added successfully');
          setShowNoteModal(false);
          setNoteText('');
      }
  };

  const handleTableEdit = (index: number, field: string, value: string) => {
      if (!localReportData || !canEdit) return;
      const numValue = parseFloat(value.replace(/,/g, ''));
      const newTableData = [...localReportData.tableData];
      newTableData[index] = { ...newTableData[index], [field]: isNaN(numValue) ? value : numValue };
      const updatedReport = { ...localReportData, tableData: newTableData };
      setLocalReportData(updatedReport);
      if (onReportUpdate) onReportUpdate(updatedReport);
  };
  
  const handleSortTable = (key: string) => {
      setTableSort(prev => ({
          key,
          dir: prev.key === key && prev.dir === 'desc' ? 'asc' : 'desc'
      }));
  };

  const updateChartType = (type: any) => {
      const updatedSections = template.sections.map(s => s.id === 'charts' ? { ...s, chartType: type } : s);
      onUpdateTemplate({ ...template, sections: updatedSections });
  };

  const toggleSeries = (dataKey: string) => {
      setVisibleSeries(prev => 
        prev.includes(dataKey) 
          ? prev.filter(s => s !== dataKey) 
          : [...prev, dataKey]
      );
  };
  
  // Handle Chart Click for Drill Down - Works on the background too
  const handleChartClick = (state: any) => {
      if (!drillDownLabel && state && state.activeLabel) {
          setDrillDownLabel(state.activeLabel);
      }
  };

  const AnnotationModal = () => (
      <div className="fixed inset-0 z-[150] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4 animate-in fade-in" aria-modal="true" role="dialog">
          <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl w-full max-w-md p-6 border border-gray-200 dark:border-gray-700 relative">
              <div className="flex justify-between items-center mb-4">
                  <h3 className="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
                      <MessageSquarePlus size={20} className="text-brand-accent"/> Add Note
                  </h3>
                  <button onClick={() => setShowNoteModal(false)} aria-label="Close note modal"><X size={20} className="text-gray-400"/></button>
              </div>
              <textarea 
                  value={noteText}
                  onChange={(e) => setNoteText(e.target.value)}
                  placeholder="Enter your observation or instruction here..."
                  className="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg p-3 text-sm text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-brand-accent h-32 resize-none"
                  autoFocus
              />
              <div className="flex justify-end gap-3 mt-4">
                  <button onClick={() => setShowNoteModal(false)} className="px-4 py-2 text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg text-sm font-medium">Cancel</button>
                  <button onClick={handleSaveNote} disabled={!noteText.trim()} className="px-4 py-2 bg-brand-accent hover:bg-brand-accentHover text-white rounded-lg text-sm font-bold disabled:opacity-50 flex items-center gap-2"><Save size={16}/> Save Note</button>
              </div>
          </div>
      </div>
  );

  const VersionHistoryModal = () => (
    <div className="fixed inset-0 z-[150] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4 animate-in fade-in" aria-modal="true" role="dialog">
      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl w-full max-w-md p-6 border border-gray-200 dark:border-gray-700 relative">
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <History size={20} className="text-brand-accent"/> Version History
          </h3>
          <button onClick={() => setShowHistory(false)} aria-label="Close history modal"><X size={20} className="text-gray-400"/></button>
        </div>
        <div className="space-y-4 max-h-[60vh] overflow-y-auto">
          {localReportData?.versions && localReportData.versions.length > 0 ? (
            localReportData.versions.map((version) => (
              <div key={version.id} className="border-b border-gray-100 dark:border-gray-700 pb-3 last:border-0">
                <div className="flex justify-between items-start mb-1">
                  <span className="font-bold text-sm text-gray-800 dark:text-gray-200">Version {version.id}</span>
                  <span className="text-xs text-gray-500">{new Date(version.date).toLocaleDateString()}</span>
                </div>
                <p className="text-xs text-gray-600 dark:text-gray-400 mb-1">{version.changes}</p>
                <div className="text-[10px] text-gray-400">Edited by {version.author}</div>
              </div>
            ))
          ) : (
            <div className="text-center text-sm text-gray-500 py-4">No version history available.</div>
          )}
        </div>
        <div className="mt-4 pt-4 border-t border-gray-100 dark:border-gray-700 flex justify-end">
            <button onClick={() => setShowHistory(false)} className="px-4 py-2 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg text-sm font-medium hover:bg-gray-200 dark:hover:bg-gray-600">Close</button>
        </div>
      </div>
    </div>
  );

  const renderSection = (section: ReportSection) => {
    if (!section.isVisible || !localReportData) return null;
    
    // Filtering logic
    let sortedTableData = [...(localReportData.tableData || [])];
    if (searchTerm || (section.id === 'table' && tableFilter)) {
        const term = (searchTerm || tableFilter).toLowerCase();
        sortedTableData = sortedTableData.filter(row => row.category.toLowerCase().includes(term));
    }

    // Sorting logic
    sortedTableData.sort((a: any, b: any) => {
        let aVal = a[tableSort.key];
        let bVal = b[tableSort.key];
        if (typeof aVal === 'string') aVal = aVal.toLowerCase();
        if (typeof bVal === 'string') bVal = bVal.toLowerCase();
        if (aVal < bVal) return tableSort.dir === 'asc' ? -1 : 1;
        if (aVal > bVal) return tableSort.dir === 'asc' ? 1 : -1;
        return 0;
    });

    const getSortIcon = (key: string) => {
        if (tableSort.key !== key) return <div className="w-3 h-3 opacity-0"></div>;
        return tableSort.dir === 'asc' ? <ChevronUp size={12}/> : <ChevronDown size={12}/>;
    };

    const sectionCommonClasses = `mb-8 p-6 bg-white dark:bg-gray-800 rounded-2xl border border-gray-100 dark:border-gray-700 shadow-sm print:shadow-none print:border-none print:p-0 page-break-inside-avoid relative group`;
    const sectionNotes = (localReportData.annotations || []).filter(a => a.sectionId === section.id);

    // Chart Theme Logic
    const gridColor = isDarkMode ? "#374151" : "#E5E7EB";
    const textColor = isDarkMode ? "#9CA3AF" : "#6B7280";
    
    // Metric names for Charts
    const primarySeriesName = localReportData.metrics?.[0]?.label || "Current Period";
    const secondarySeriesName = "Previous Period";

    // Chart Rendering Helper
    const renderChart = () => {
        const ChartComponent = section.chartType === 'bar' ? RechartsBarChart : 
                             section.chartType === 'line' ? RechartsLineChart : 
                             RechartsAreaChart; // Default to Area if undefined or 'area'
        
        // Ensure we pass the right components based on chart type
        const commonProps = {
            data: chartDataToRender,
            margin: { top: 10, right: 30, left: 0, bottom: 0 },
            onClick: handleChartClick,
            className: "cursor-pointer"
        };

        return (
            <ResponsiveContainer width="100%" height="100%" minWidth={0}>
                 <ChartComponent {...commonProps}>
                    <defs>
                        <linearGradient id="colorPrimary" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor={theme.primary} stopOpacity={0.3}/>
                        <stop offset="95%" stopColor={theme.primary} stopOpacity={0}/>
                        </linearGradient>
                         <linearGradient id="colorSecondary" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="5%" stopColor={theme.secondary} stopOpacity={0.3}/>
                            <stop offset="95%" stopColor={theme.secondary} stopOpacity={0}/>
                        </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={gridColor} strokeOpacity={0.5} />
                    <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: textColor, fontSize: 12}} dy={10} />
                    <YAxis axisLine={false} tickLine={false} tick={{fill: textColor, fontSize: 12}} />
                    <Tooltip content={<CustomTooltip />} cursor={{fill: 'rgba(0,0,0,0.05)'}} />
                    <Legend onClick={(e) => toggleSeries(e.dataKey as string)} formatter={(value, entry) => (<span className={`cursor-pointer ${!visibleSeries.includes(entry.dataKey as string) ? 'opacity-40 text-gray-400 decoration-line-through' : 'font-bold'}`} style={{color: textColor}}>{value}</span>)} />
                    
                    {visibleSeries.includes('primary') && (
                        section.chartType === 'bar' ? 
                        <Bar dataKey="primary" fill={theme.primary} name={primarySeriesName} radius={[4, 4, 0, 0]} barSize={32} /> :
                        section.chartType === 'line' ?
                        <Line type="monotone" dataKey="primary" stroke={theme.primary} strokeWidth={3} dot={{r: 4}} activeDot={{r: 6}} name={primarySeriesName} /> :
                        <Area type="monotone" dataKey="primary" stroke={theme.primary} fill={`url(#colorPrimary)`} fillOpacity={0.6} strokeWidth={3} name={primarySeriesName} activeDot={{r: 6}} />
                    )}
                    
                    {visibleSeries.includes('secondary') && (
                         section.chartType === 'bar' ? 
                         <Bar dataKey="secondary" fill={theme.secondary} name={secondarySeriesName} radius={[4, 4, 0, 0]} barSize={32} /> :
                         section.chartType === 'line' ?
                         <Line type="monotone" dataKey="secondary" stroke={theme.secondary} strokeWidth={3} dot={{r: 4}} activeDot={{r: 6}} name={secondarySeriesName} /> :
                         <Area type="monotone" dataKey="secondary" stroke={theme.secondary} fill={`url(#colorSecondary)`} fillOpacity={0.3} strokeWidth={3} name={secondarySeriesName} activeDot={{r: 6}} />
                    )}
                 </ChartComponent>
            </ResponsiveContainer>
        );
    };

    return (
      <section key={section.id} id={`section-${section.id}`} className={sectionCommonClasses} style={{ order: section.order }}>
        {/* Section Actions */}
        <div className="absolute top-4 right-4 flex gap-2 no-print z-20" data-html2canvas-ignore="true">
            <button 
                onClick={(e) => { e.stopPropagation(); openNoteModal(section.id); }} 
                className="p-1.5 bg-gray-100 dark:bg-gray-700 rounded-md text-gray-500 hover:text-brand-accent transition-colors shadow-sm opacity-0 group-hover:opacity-100 focus:opacity-100" 
                title="Add Note"
            >
                <MessageSquarePlus size={14} />
            </button>
        </div>

        {/* Annotations Display */}
        {sectionNotes.length > 0 && (
             <div className="absolute -left-2 top-6 -translate-x-full pr-2 hidden xl:block no-print w-48">
                <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-100 dark:border-yellow-900/50 p-3 rounded-lg shadow-sm">
                    <div className="text-[10px] font-bold text-yellow-600 dark:text-yellow-400 uppercase mb-2 flex items-center gap-1"><MessageSquarePlus size={10}/> Notes</div>
                    {sectionNotes.map(note => (
                        <div key={note.id} className="text-xs text-gray-600 dark:text-gray-300 mb-2 last:mb-0 border-l-2 border-yellow-400 pl-2">"{note.text}"<div className="text-[10px] text-gray-400 mt-0.5">{note.author}</div></div>
                    ))}
                </div>
            </div>
        )}

        {/* Section Header */}
        <div className="flex justify-between items-center mb-6 border-b border-gray-100 dark:border-gray-700 pb-4">
            <h2 className="text-xl font-bold tracking-tight text-gray-900 dark:text-white uppercase flex items-center gap-2" style={{ fontFamily: theme.font }}>
                {section.id === 'summary' && <FileText size={20} className="text-brand-accent"/>}
                {section.id === 'metrics' && <Layout size={20} className="text-brand-accent"/>}
                {section.id === 'charts' && <BarChart size={20} className="text-brand-accent"/>}
                {section.id === 'risks' && <AlertTriangle size={20} className="text-brand-accent"/>}
                {section.id === 'insights' && <Lightbulb size={20} className="text-brand-accent"/>}
                {section.id === 'table' && <Grid size={20} className="text-brand-accent"/>}
                {section.id === 'outlook' && <TrendingUp size={20} className="text-brand-accent"/>}
                {section.id === 'predictive' && <Activity size={20} className="text-brand-accent"/>}
                {section.id === 'competitors' && <Target size={20} className="text-brand-accent"/>}
                {section.label}
            </h2>
            
            {section.id === 'header' && (
                <div className="flex items-center gap-2 no-print">
                     {localReportData.dataQuality && (
                         <div className={`text-[10px] font-bold px-2 py-1 rounded border flex items-center gap-1 cursor-help ${
                             localReportData.dataQuality.score > 90 ? 'bg-green-50 text-green-700 border-green-200' : 'bg-orange-50 text-orange-700 border-orange-200'
                         }`} title={`Last Updated: ${localReportData.dataQuality.lastUpdated}`}>
                             <Activity size={10}/> DQ Score: {localReportData.dataQuality.score}/100
                         </div>
                     )}
                     <div className={`flex items-center gap-2 overflow-hidden transition-all duration-300 ${showSearch ? 'w-64 opacity-100' : 'w-0 opacity-0'}`}>
                         <input type="text" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} placeholder="Find in report..." className="w-full bg-gray-100 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg px-3 py-1.5 text-xs text-gray-900 dark:text-white outline-none focus:ring-1 focus:ring-brand-accent"/>
                     </div>
                     <button onClick={() => {setShowSearch(!showSearch); if(showSearch) setSearchTerm('');}} className={`p-1.5 rounded-lg transition-colors ${showSearch || searchTerm ? 'text-brand-accent bg-brand-accent/10' : 'text-gray-400 hover:text-gray-600 dark:hover:text-gray-200'}`}>{showSearch ? <X size={16}/> : <Search size={16}/>}</button>
                </div>
            )}

            {section.id === 'charts' && (
                 <div className="flex bg-gray-100 dark:bg-gray-700 rounded-lg p-1 no-print">
                     <button onClick={() => updateChartType('bar')} className={`p-1.5 rounded ${section.chartType === 'bar' ? 'bg-white dark:bg-gray-600 shadow-sm' : 'text-gray-500'}`}><BarChart size={14}/></button>
                     <button onClick={() => updateChartType('line')} className={`p-1.5 rounded ${section.chartType === 'line' ? 'bg-white dark:bg-gray-600 shadow-sm' : 'text-gray-500'}`}><TrendingUp size={14}/></button>
                     <button onClick={() => updateChartType('area')} className={`p-1.5 rounded ${section.chartType === 'area' ? 'bg-white dark:bg-gray-600 shadow-sm' : 'text-gray-500'}`}><Activity size={14}/></button>
                     <button onClick={() => updateChartType('radar')} className={`p-1.5 rounded ${section.chartType === 'radar' ? 'bg-white dark:bg-gray-600 shadow-sm' : 'text-gray-500'}`}><RadarIcon size={14}/></button>
                 </div>
            )}
            
            {section.id === 'table' && (
                <div className="flex items-center gap-2 no-print">
                    <input type="text" value={tableFilter} onChange={(e) => setTableFilter(e.target.value)} placeholder="Filter..." className="bg-gray-100 dark:bg-gray-700 border-none rounded-lg pl-3 pr-3 py-1.5 text-xs w-32 focus:w-48 transition-all"/>
                </div>
            )}
        </div>

        <div className="text-gray-700 dark:text-gray-300">
          {section.id === 'header' && (
              <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                  <div>
                      <h1 className="text-3xl md:text-4xl font-black text-gray-900 dark:text-white mb-2 tracking-tight">
                          {isEditingTitle ? (
                              <input autoFocus className="bg-transparent border-b border-gray-300 dark:border-gray-600 focus:border-brand-accent outline-none w-full" value={localReportData.title} onChange={(e) => { const newData = {...localReportData, title: e.target.value}; setLocalReportData(newData); if(onReportUpdate) onReportUpdate(newData); }} onBlur={() => setIsEditingTitle(false)} />
                          ) : (
                              <span onClick={() => canEdit && setIsEditingTitle(true)} className={canEdit ? "cursor-pointer hover:text-brand-accent transition-colors" : ""}>{localReportData.title}</span>
                          )}
                      </h1>
                      <div className="flex items-center gap-4 text-sm text-gray-500 font-medium">
                          <span className="flex items-center gap-1"><Clock size={14}/> {localReportData.date}</span>
                          <span className="flex items-center gap-1"><Users size={14}/> {localReportData.audience}</span>
                      </div>
                  </div>
                  {branding?.logoUrl && <img src={branding.logoUrl} alt="Logo" className="h-12 object-contain" />}
              </div>
          )}

          {section.id === 'metrics' && (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              {localReportData.metrics.map((m, i) => (
                <MetricCard key={i} metric={m} themeColor={theme.primary} />
              ))}
            </div>
          )}

          {section.id === 'summary' && (
            <div>
                {localReportData.executiveBrief ? (
                    <div>
                        <div className="flex border-b border-gray-200 dark:border-gray-700 mb-4 no-print">
                            <button onClick={() => setActivePersona('cro')} className={`pb-2 px-4 text-sm font-bold border-b-2 transition-colors flex items-center gap-2 ${activePersona === 'cro' ? 'border-brand-accent text-brand-accent' : 'border-transparent text-gray-500'}`}>
                                <Briefcase size={14}/> Sales (CRO)
                            </button>
                            <button onClick={() => setActivePersona('cfo')} className={`pb-2 px-4 text-sm font-bold border-b-2 transition-colors flex items-center gap-2 ${activePersona === 'cfo' ? 'border-brand-accent text-brand-accent' : 'border-transparent text-gray-500'}`}>
                                <DollarSign size={14}/> Finance (CFO)
                            </button>
                            <button onClick={() => setActivePersona('coo')} className={`pb-2 px-4 text-sm font-bold border-b-2 transition-colors flex items-center gap-2 ${activePersona === 'coo' ? 'border-brand-accent text-brand-accent' : 'border-transparent text-gray-500'}`}>
                                <Activity size={14}/> Ops (COO)
                            </button>
                        </div>
                        <div className="prose dark:prose-invert max-w-none text-gray-600 dark:text-gray-300">
                             <MarkdownText 
                                content={
                                    activePersona === 'cfo' ? localReportData.executiveBrief.cfoView : 
                                    activePersona === 'coo' ? localReportData.executiveBrief.cooView : 
                                    localReportData.executiveBrief.croView
                                } 
                                highlight={searchTerm} 
                            />
                        </div>
                    </div>
                ) : (
                    <MarkdownText content={localReportData.summary} highlight={searchTerm} className="prose dark:prose-invert max-w-none text-gray-600 dark:text-gray-300" />
                )}
                
                {localReportData.marketContext && (
                    <div className="mt-6 bg-blue-50 dark:bg-blue-900/10 p-4 rounded-xl border border-blue-100 dark:border-blue-900/30">
                        <div className="text-xs font-bold text-blue-600 dark:text-blue-400 uppercase mb-1 flex items-center gap-1"><Globe size={12}/> Market Context</div>
                        <MarkdownText content={localReportData.marketContext} className="text-sm text-blue-900 dark:text-blue-200" />
                    </div>
                )}
            </div>
          )}

          {section.id === 'predictive' && (
             <PredictiveAnalytics scenarios={localReportData.scenarios || []} baseData={localReportData.chartData} themeColor={theme.primary} />
          )}
          
          {section.id === 'competitors' && localReportData.competitors && localReportData.competitors.length > 0 && (
              <div className="h-[300px]">
                  <ResponsiveContainer width="100%" height="100%" minWidth={0}>
                      <RechartsBarChart data={localReportData.competitors} layout="vertical" margin={{top: 5, right: 30, left: 40, bottom: 5}}>
                          <CartesianGrid strokeDasharray="3 3" horizontal={true} vertical={false} stroke={gridColor}/>
                          <XAxis type="number" hide/>
                          <YAxis dataKey="name" type="category" width={100} tick={{fill: textColor, fontSize: 12, fontWeight: 'bold'}} axisLine={false} tickLine={false}/>
                          <Tooltip cursor={{fill: 'transparent'}} content={<CustomTooltip />}/>
                          <Legend />
                          <Bar dataKey="marketShare" name="Market Share %" fill={theme.primary} radius={[0, 4, 4, 0]} barSize={20} />
                          <Bar dataKey="growth" name="YoY Growth %" fill={theme.secondary} radius={[0, 4, 4, 0]} barSize={20} />
                      </RechartsBarChart>
                  </ResponsiveContainer>
              </div>
          )}

          {section.id === 'charts' && (
            <div ref={chartContainerRef} className="h-[400px] w-full relative group">
                {drillDownLabel && (
                    <button onClick={() => setDrillDownLabel(null)} className="absolute top-0 left-10 z-10 flex items-center gap-1 text-xs font-bold text-gray-500 hover:text-brand-accent bg-white/80 dark:bg-gray-800/80 px-2 py-1 rounded shadow-sm border border-gray-200 dark:border-gray-700 backdrop-blur-sm transition-colors">
                        <ChevronLeft size={12} /> Back to Overview
                    </button>
                )}
                
                {section.chartType === 'radar' ? (
                   localReportData.strategicMap && localReportData.strategicMap.length > 0 ? (
                    <ResponsiveContainer width="100%" height="100%" minWidth={0}>
                        <RadarChart outerRadius={150} data={localReportData.strategicMap}>
                            <PolarGrid stroke={gridColor} />
                            <PolarAngleAxis dataKey="dim" tick={{ fill: textColor, fontSize: 11, fontWeight: 'bold' }} />
                            <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                            <Radar name="Current Performance" dataKey="A" stroke={theme.primary} fill={theme.primary} fillOpacity={0.4} />
                            <Radar name="Target/Benchmark" dataKey="B" stroke={theme.secondary} fill={theme.secondary} fillOpacity={0.1} />
                            <Legend wrapperStyle={{fontSize: '12px', color: textColor}} />
                            <Tooltip content={<CustomTooltip />} itemStyle={{color: '#fff'}}/>
                        </RadarChart>
                    </ResponsiveContainer>
                   ) : (
                       <div className="flex items-center justify-center h-full text-gray-400 text-sm">
                           No strategic map data available for this report.
                       </div>
                   )
                ) : (
                    renderChart()
                )}
                
              {!drillDownLabel && section.chartType !== 'radar' && (
                  <div className="absolute top-2 right-10 text-[10px] text-gray-400 pointer-events-none bg-white/50 dark:bg-gray-800/50 px-2 py-1 rounded">
                      Click column to drill down
                  </div>
              )}
            </div>
          )}

          {section.id === 'table' && (
            <div className="overflow-x-auto rounded-xl border border-gray-200 dark:border-gray-700">
              <table className="w-full text-sm text-left">
                <thead className="bg-gray-50 dark:bg-gray-900 text-gray-500 uppercase font-bold text-xs">
                  <tr>
                    <th className="px-6 py-4 cursor-pointer hover:text-gray-700" onClick={() => handleSortTable('category')}>Category {getSortIcon('category')}</th>
                    <th className="px-6 py-4 text-right cursor-pointer hover:text-gray-700" onClick={() => handleSortTable('primary')}>Current {getSortIcon('primary')}</th>
                    <th className="px-6 py-4 text-right cursor-pointer hover:text-gray-700" onClick={() => handleSortTable('secondary')}>Previous {getSortIcon('secondary')}</th>
                    <th className="px-6 py-4 text-right cursor-pointer hover:text-gray-700" onClick={() => handleSortTable('contribution')}>Contribution {getSortIcon('contribution')}</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100 dark:divide-gray-700 bg-white dark:bg-gray-800">
                  {sortedTableData.map((row, i) => (
                    <tr key={i} className="hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors">
                      <td className="px-6 py-4 font-medium text-gray-900 dark:text-white">
                          {canEdit ? <input className="bg-transparent border-none outline-none w-full" value={row.category} onChange={(e) => handleTableEdit(i, 'category', e.target.value)} /> : row.category}
                      </td>
                      <td className="px-6 py-4 text-right font-mono">{row.primary.toLocaleString()}</td>
                      <td className="px-6 py-4 text-right font-mono text-gray-500">{row.secondary.toLocaleString()}</td>
                      <td className="px-6 py-4 text-right">
                        <div className="flex items-center justify-end gap-2">
                          <span className="font-bold">{row.contribution}%</span>
                          <div className="w-16 h-1.5 bg-gray-100 dark:bg-gray-700 rounded-full overflow-hidden">
                             <div className="h-full rounded-full" style={{ width: `${Math.min(row.contribution, 100)}%`, backgroundColor: theme.primary }}></div>
                          </div>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
          
          {section.id === 'insights' && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {localReportData.insights.map((insight, idx) => (
                      <div key={idx} className="flex gap-4 p-4 rounded-xl bg-gray-50 dark:bg-gray-900/50 border border-gray-100 dark:border-gray-700 hover:border-brand-accent/30 transition-colors relative">
                          <div className="flex-shrink-0 w-8 h-8 rounded-full bg-brand-accent/10 flex items-center justify-center text-brand-accent font-bold text-sm">{idx + 1}</div>
                          <div className="text-sm leading-relaxed text-gray-700 dark:text-gray-300">
                             <MarkdownText content={insight.text} highlight={searchTerm} />
                             {insight.source && <div className="text-xs text-gray-400 mt-1">Source: {insight.source}</div>}
                          </div>
                      </div>
                  ))}
              </div>
          )}

          {section.id === 'risks' && (
              viewTypeRisk === 'matrix' ? (
                   <RiskMatrix risks={localReportData.risks} themeColor={theme.primary} />
              ) : (
                <div className="space-y-3">
                    {localReportData.risks.map((risk, idx) => (
                        <div key={idx} className="flex items-start gap-4 p-4 rounded-xl border border-l-4 bg-white dark:bg-gray-800 shadow-sm transition-transform hover:translate-x-1"
                             style={{ borderLeftColor: risk.priority === 'Critical' ? '#EF4444' : risk.priority === 'Monitor' ? '#F59E0B' : '#10B981', borderColor: 'rgba(229, 231, 235, 0.5)' }}>
                            <div className={`mt-1 p-1.5 rounded-full ${risk.priority === 'Critical' ? 'bg-red-100 text-red-600' : risk.priority === 'Monitor' ? 'bg-orange-100 text-orange-600' : 'bg-green-100 text-green-600'}`}>
                                <AlertTriangle size={16} />
                            </div>
                            <div>
                                <h4 className="font-bold text-gray-900 dark:text-white text-sm mb-1">{risk.description}</h4>
                                <div className="flex gap-3 text-xs font-medium uppercase tracking-wider text-gray-500">
                                    <span>Impact: <span className={risk.impact === 'High' ? 'text-red-500' : 'text-gray-700 dark:text-gray-300'}>{risk.impact}</span></span>
                                    <span>Priority: <span className={risk.priority === 'Critical' ? 'text-red-500' : 'text-gray-700 dark:text-gray-300'}>{risk.priority}</span></span>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
              )
          )}
          
          {section.id === 'recommendations' && (
              <div className="space-y-3">
                  {localReportData.recommendations.map((rec, idx) => (
                      <div key={idx} className="p-4 rounded-xl border transition-all bg-white dark:bg-gray-800 border-gray-100 dark:border-gray-700 hover:border-gray-300">
                          <div className="flex justify-between items-start mb-2">
                              <h4 className="font-bold text-gray-900 dark:text-white text-sm">{rec.title}</h4>
                              <div className="flex gap-2">
                                  <span className={`text-[10px] uppercase font-bold px-1.5 py-0.5 rounded ${rec.impact === 'High' ? 'bg-red-100 text-red-700' : 'bg-gray-100 text-gray-600'}`}>Imp: {rec.impact}</span>
                                  <span className={`text-[10px] uppercase font-bold px-1.5 py-0.5 rounded ${rec.effort === 'High' ? 'bg-orange-100 text-orange-700' : 'bg-green-100 text-green-700'}`}>Eff: {rec.effort}</span>
                              </div>
                          </div>
                          <p className="text-sm text-gray-600 dark:text-gray-300 mb-3">{rec.description}</p>
                      </div>
                  ))}
              </div>
          )}
          
          {section.id === 'outlook' && (
              <div className="bg-blue-50 dark:bg-blue-900/10 p-6 rounded-xl border border-blue-100 dark:border-blue-900/30">
                  <MarkdownText content={localReportData.outlook} highlight={searchTerm} className="text-sm text-blue-900 dark:text-blue-200 leading-relaxed font-medium" />
              </div>
          )}

          {section.id === 'footer' && (
              <div className="text-center text-xs text-gray-400 mt-8 pt-8 border-t border-gray-100 dark:border-gray-800">
                  <p>Generated by {branding?.companyName || 'ReportGenius AI'} • {new Date().getFullYear()}</p>
                  <p className="mt-1 opacity-60">Confidential - Internal Use Only</p>
                  <div className="flex justify-center gap-4 mt-2">
                      <a href="#" className="hover:text-brand-accent">Privacy Policy</a>
                      <a href="#" className="hover:text-brand-accent">Terms of Service</a>
                  </div>
              </div>
          )}
        </div>
      </section>
    );
  };

  if (!localReportData) return <div className="p-10 text-center">Loading...</div>;

  return (
    <div className={`transition-all duration-300 ${isVisible ? 'opacity-100' : 'opacity-0 hidden'}`}>
      {showHistory && <VersionHistoryModal />}
      {showNoteModal && <AnnotationModal />}
      
      <div 
        id="report-container"
        className={`mx-auto transition-all duration-500 ease-in-out ${viewMode === 'dashboard' ? 'max-w-full px-4' : 'max-w-4xl'}`}
      >
        {viewMode === 'dashboard' ? (
           <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6 auto-rows-min">
              {template.sections.filter(s => s.isVisible).sort((a, b) => (a.order || 0) - (b.order || 0)).map(section => (
                  <div key={section.id} className={section.id === 'metrics' || section.id === 'table' || section.id === 'charts' ? 'col-span-full' : ''}>
                      {renderSection(section)}
                  </div>
              ))}
           </div>
        ) : (
           <div className="flex flex-col gap-4">
              {template.sections.filter(s => s.isVisible).sort((a, b) => (a.order || 0) - (b.order || 0)).map(section => renderSection(section))}
           </div>
        )}
      </div>
    </div>
  );
};

export default ReportView;
